#!/bin/bash

show_help() {
cat << EOF
Usage: $0 [-hvc] [-o OUTPUT_PDF] [-b BIBLIOGRAPHY] [-t TITLE_TEX] MARKDOWN_FILE
Compile .md files to DSTU looking pdf docs
    -h          display this help and exit
    -v          verbose mode
    -b          bibliography file (.bib format)
    -c          use chapter level division
    -t          custom title page (.tex format)
    -o          path to output pdf file
EOF
}

MD_FILE=
TITLE_TEX=
BIBLIOGRAPHY=
USE_CHAPTER_DIVISION=0
VERBOSE=0
OUT_PDF=out.pdf

OPTIND=1
while getopts vhcb:o:t: opt; do
    case $opt in
        h)
            show_help
            exit 0
            ;;
        v)  VERBOSE=$((VERBOSE+1))
            ;;
        c)  USE_CHAPTER_DIVISION=$((USE_CHAPTER_DIVISION+1))
            ;;
        o)  OUT_PDF=$OPTARG
            ;;
        b)  BIBLIOGRAPHY=$OPTARG
            ;;
        t)  TITLE_TEX=$OPTARG
            ;;
        *)
            show_help >&2
            exit 1
            ;;
    esac
done
shift "$((OPTIND-1))"

if [ $# -eq 1 ]; then
    MD_FILE=$1
else
    show_help
    exit 0
fi

if [ -n "$BIBLIOGRAPHY" ]; then
    BIBLIOGRAPHY="--bibliography=input_files/$BIBLIOGRAPHY"
fi

if [ -n "$TITLE_TEX" ]; then
    TITLE_TEX="--include-before-body=input_files/$TITLE_TEX"
fi

if [ $VERBOSE -ge 1 ]; then
    VERBOSE="--verbose"
else
    VERBOSE=""
fi

if [ $USE_CHAPTER_DIVISION -ge 1 ]; then
    MAP_ARG=reporttype:extreport
    LEVEL_DIVISION=chapter
else
    MAP_ARG=reporttype:extarticle
    LEVEL_DIVISION=section
fi

docker run --rm \
  -v "$(pwd)":/home/pandocuser/data \
  -v "$(pwd)"/input_files:/home/pandocuser/data/input_files \
  local/dstu-pandoc input_files/$MD_FILE \
    --citeproc \
    --top-level-division=$LEVEL_DIVISION \
    -M $MAP_ARG \
    -o "input_files/$OUT_PDF" \
    --from markdown+table_captions+multiline_tables+header_attributes+fancy_lists \
    --listings \
    --template template.tex \
    --pdf-engine=xelatex \
    --csl=dstu-references.csl \
    $TITLE_TEX $BIBLIOGRAPHY $VERBOSE
